<div>
    <div class="flex flex-row items-center justify-between p-4 bg-gray-100 rounded shadow">
        <h1 class="font-bold text-gray-700"><?= $title ?> - #<?= $budget->id ?></h1>
    </div>

    <div class="flex flex-col gap-2 p-4 mt-2 bg-white rounded shadow">
        <div class="w-full">
            <label for="budget_customer_id" class="input-label">Cliente:</label>
            <select name="budget[customer_id]" id="budget_customer_id" class="select" disabled>
                <?php foreach ($customers as $customer) { ?>
                    <option
                        value="<?= $customer->id ?>"
                        <?= $customer->id === $budget->customer_id ? 'selected' : '' ?>>
                        <?= $customer->id . ' - ' .  $customer->name ?>
                    </option>
                <?php } ?>
            </select>
        </div>

        <div class="flex flex-row items-end justify-between gap-2">
            <div class="w-full">
                <label for="product_id" class="input-label">Produto:</label>
                <select id="product_id" class="select">
                    <?php foreach ($products as $product) { ?>
                        <option value="<?= $product->id ?>"><?= $product->id . ' - ' .  $product->name ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="w-full">
                <label for="product_quantity" class="input-label">Quantidade:</label>
                <input type="number" placeholder="0" id="product_quantity" class="input" min="1" value="1">
            </div>

            <div class="w-full">
                <label for="product_price" class="input-label">Preço:</label>
                <div class="flex flex-row">
                    <span class="flex items-center justify-center h-12 px-4 text-lg leading-6 text-center border border-gray-600 rounded-md rounded-e-none">R$</span>
                    <input type="number" id="product_price" class="input !rounded-s-none" min="0.00" step="0.01" placeholder="0.00">
                </div>
            </div>

            <button
                class="p-3 font-bold text-white bg-green-700 rounded"
                type="button"
                id="add-product">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
            </button>
        </div>

        <input value="<?= $budget->id ?>" id="budget_id" hidden>

        <div class="mt-4">
            <h3 class="text-lg font-semibold">Produtos:</h3>

            <table class="min-w-full bg-white rounded-lg shadow">
                <thead>
                    <tr class="text-sm font-semibold text-left text-gray-700 uppercase bg-gray-200">
                        <th class="px-4 py-2 text-center border-b">N°</th>
                        <th class="px-4 py-2 text-center border-b">Produto</th>
                        <th class="px-4 py-2 text-center border-b">Quantidade</th>
                        <th class="px-4 py-2 text-center border-b">Valor Un.</th>
                        <th class="px-4 py-2 text-center border-b">Valor Total</th>
                        <th class="px-4 py-2 text-center border-b">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($budget->items as $k => $product): ?>
                        <tr class="hover:bg-gray-50">
                            <td class="py-2 font-bold text-center text-gray-800 border-b"><?= $k + 1; ?></td>
                            <td class="py-2 font-bold text-center text-gray-800 border-b"><?= $product->product->name; ?></td>
                            <td class="py-2 font-bold text-center text-gray-800 border-b"><?= $product->quantity; ?></td>
                            <td class="py-2 font-bold text-center text-gray-800 border-b">R$ <?= number_format($product->unit_price, 2, ',', '.'); ?></td>
                            <td class="py-2 font-bold text-center text-gray-800 border-b">R$ <?= number_format($product->total_price, 2, ',', '.'); ?></td>
                            <td class="py-2 font-bold text-center text-gray-800 border-b">
                                <button class="remove-product" data-id="<?= $product->id ?>">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="red" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                                    </svg>
                                </button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
