<div>
    <div class="flex flex-row items-center justify-between p-4 bg-gray-100 rounded shadow">
        <h1 class="font-bold text-gray-700"><?= $title ?></h1>
    </div>

    <form action="<?= route('admin.budgets.create') ?>" method="POST">
        <div class="flex flex-col gap-2 p-4 mt-2 bg-white rounded shadow">
            <div class="flex flex-row items-end justify-between gap-2">
                <div class="w-full">
                    <label for="budget_customer_id" class="input-label">Cliente:</label>
                    <select name="budget[customer_id]" id="budget_customer_id" class="select">
                        <?php foreach ($customers as $customer) { ?>
                            <option value="<?= $customer->id ?>"><?= $customer->id . ' - ' .  $customer->name ?></option>
                        <?php } ?>
                    </select>
                </div>

                <button
                    class="p-3 font-bold text-white bg-green-700 rounded"
                    type="button"
                    id="select-customer">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                    </svg>
                </button>
            </div>
        </div>
    </form>
</div>
