<div>
    <div class="flex flex-row items-center justify-between p-4 bg-gray-100 rounded-t-lg shadow">
        <h1 class="font-bold text-gray-700"><?= $title ?></h1>
    </div>

    <div class="p-4 rounded-b-lg shadow">
        <p><span class="font-bold text-gray-800">Cliente:</span> <?= $budget->customer->name  ?></p>
        <p><span class="font-bold text-gray-800">Status:</span>
            <?php
            switch ($budget->status) {
                case 'pending':
                    echo 'Pendente Aprovação';
                    break;
                default:
                    echo 'Pendente';
                    break;
            }
            ?>
        </p>
        <p><span class="font-bold text-gray-800">Pago?</span> <?= $budget->payed ? 'Pago' : 'Pendente' ?></p>
        <p><span class="font-bold text-gray-800">Quantidade de Produtos:</span> <?= count($budget->products) ?></p>
        <p><span class="font-bold text-gray-800">Total:</span>R$ <?= number_format($budget->total, 2, ',', '.')  ?></p>
    </div>

    <div class="p-4 rounded-b-lg shadow">
        <table class="min-w-full bg-white">
            <thead>
                <tr class="border">
                    <th class="py-2 border">Quantidade</th>
                    <th class="py-2 border">Produto</th>
                    <th class="py-2 border">Preço Unitário</th>
                    <th class="py-2 border">Valor Total</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($budget->items as $item): ?>
                    <tr>
                        <td class="px-4 py-2 border"><?= $item->quantity ?></td>
                        <td class="px-4 py-2 border"><?= $item->product->name ?></td>
                        <td class="px-4 py-2 border">R$ <?= number_format($item->unit_price, 2, ',', '.') ?></td>
                        <td class="px-4 py-2 border">R$ <?= number_format($item->unit_price * $item->quantity, 2, ',', '.') ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
