<div>
    <div class="flex flex-row items-center justify-between p-4 bg-gray-100 rounded-t-lg shadow">
        <h1 class="font-bold text-gray-700"><?= $title ?></h1>
    </div>

    <div class="p-4 rounded-b-lg shadow">
        <p><span class="font-bold text-gray-800">Cliente:</span> <?= $budget->customer->name  ?></p>
        <p><span class="font-bold text-gray-800">Status:</span>
            <?php
            switch ($budget->status) {
                case 'pending':
                    echo 'Pendente Aprovação';
                    break;
                default:
                    echo 'Pendente';
                    break;
            }
            ?>
        </p>
        <p><span class="font-bold text-gray-800">Pago?</span> <?= $budget->payed ? 'Pago' : 'Pendente' ?></p>
        <p><span class="font-bold text-gray-800">Quantidade de Produtos:</span> <?= count($budget->products) ?></p>
        <p><span class="font-bold text-gray-800">Total:</span>R$ <?= number_format($budget->total, 2, ',', '.')  ?></p>
    </div>

    <div class="mt-4">
        <h3 class="text-lg font-semibold">Produtos:</h3>

        <table class="min-w-full bg-white rounded-lg shadow">
            <thead>
                <tr class="text-sm font-semibold text-left text-gray-700 uppercase bg-gray-200">
                    <th class="px-4 py-2 text-center border-b">N°</th>
                    <th class="px-4 py-2 text-center border-b">Produto</th>
                    <th class="px-4 py-2 text-center border-b">Quantidade</th>
                    <th class="px-4 py-2 text-center border-b">Valor Un.</th>
                    <th class="px-4 py-2 text-center border-b">Valor Total</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($budget->items as $k => $product): ?>
                    <tr class="hover:bg-gray-50">
                        <td class="py-2 font-bold text-center text-gray-800 border-b"><?= $k + 1; ?></td>
                        <td class="py-2 font-bold text-center text-gray-800 border-b"><?= $product->product->name; ?></td>
                        <td class="py-2 font-bold text-center text-gray-800 border-b"><?= $product->quantity; ?></td>
                        <td class="py-2 font-bold text-center text-gray-800 border-b">R$ <?= number_format($product->unit_price, 2, ',', '.'); ?></td>
                        <td class="py-2 font-bold text-center text-gray-800 border-b">R$ <?= number_format($product->total_price, 2, ',', '.'); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="flex flex-col mt-2 font-bold rounded">
            <div class="flex flex-row items-center justify-between">
                <h1>Total do orçamento:</h1>
                <h1 class="text-xl font-black text-green-600 uppercase">R$ <?= number_format($budget->total, 2, ',', '.') ?></h1>
            </div>
        </div>
    </div>
</div>
