<form action="/login" method="POST">
    <div>
        <label for="user_email">Email</label>
        <input id="user_email" type="email" name="user[email]" placeholder="Enter email">
    </div>
    <div>
        <label for="user_password">Senha</label>
        <input id="user_password" type="password" name="user[password]" placeholder="Password">
    </div>
    <div>
        <input type="submit" value="Entrar">
    </div>
</form>
