<div class="flex flex-col justify-between p-12 bg-gray-100 rounded shadow">
    <div class="mb-4">
        <h1 class="text-2xl font-semibold">Mão na Roda</h1>
        <p class="text-gray-800">O assistente que você precisa para sua oficina</p>
    </div>

    <form action="/login" method="POST">
        <div class="flex flex-col gap-4">
            <div>
                <label for="user_email" class="input-label">Email:</label>
                <input id="user_email" type="email" name="user[email]" placeholder="Enter email" class="input">
            </div>

            <div>
                <label for="user_password" class="input-label">Senha:</label>
                <input id="user_password" type="password" name="user[password]" placeholder="Password" class="input">
            </div>

            <button class="w-full mt-2 btn-primary" type="submit">Entrar</button>
        </div>
    </form>
</div>
