<div class="flex flex-col justify-center items-end">
    <nav>
        <ul class="flex items-center -space-x-px h-8 text-sm">
            <?php if ($paginator->hasPreviousPage()) : ?>
                <li>
                    <a class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700" href="<?= route($paginator->getRouteName(), ['page' => $paginator->previousPage()]) ?>">
                        <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4" />
                        </svg>
                    </a>
                </li>
            <?php else : ?>
                <li class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-gray-200 border border-e-0 border-gray-300 rounded-s-lg">
                    <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4" />
                    </svg>
                </li>
            <?php endif; ?>

            <?php for ($page = 1; $page <= $paginator->totalOfPages(); $page++) : ?>
                <li>
                    <a class="flex items-center justify-center px-3 h-8 leading-tight <?= $paginator->isPage($page) ? 'bg-gray-100 text-gray-700' : 'text-gray-500' ?> border border-gray-300 hover:bg-gray-100 hover:text-gray-700" href="<?= route($paginator->getRouteName(), ['page' => $page]) ?>"><?= $page ?></a>
                </li>
            <?php endfor; ?>

            <?php if ($paginator->hasNextPage()) : ?>
                <li>
                    <a class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700" href="<?= route($paginator->getRouteName(), ['page' => $paginator->nextPage()]) ?>">
                        <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
                        </svg>
                    </a>
                </li>
            <?php else : ?>
                <li class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-gray-200 border border-gray-300 rounded-e-lg">
                    <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
                    </svg>
                </li>
            <?php endif; ?>
        </ul>
    </nav>

    <div>
        <span class="text-gray-500"><?= $paginator->entriesInfo() ?></span>
    </div>
</div>
