<div>
  <div>
    <div>
      <input type="text" placeholder="Procurar produtos">
      <button type="button">
        Pesquisar...
      </button>
    </div>
  </div>
  <div>
    <a href="/pages/products/new.php">
      <i></i>
      Cadastrar Produto
    </a>
  </div>
</div>

<table>
  <thead>
    <th>ID</th>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Marca</th>
    <th>Preço</th>
    <th>Ações</th>
  </thead>
  <tbody>
    <?php foreach ($products as $index => $product) : ?>
      <tr>
        <td><a href="/pages/products/show.php?id=<?= $index ?>">#<?= $index ?></a></td>
        <td><?= explode('|', $product)[0] ?></td>
        <td><?= explode('|', $product)[1] ?></td>
        <td><?= explode('|', $product)[2] ?></td>
        <td>R$ <?= explode('|', $product)[3] ?></td>
        <td>
          <a href="/pages/products/edit.php?id=<?= $index ?>">
            <button>
              Editar
            </button>
          </a>

          <form action="delete.php" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="product[id]" value="<?= $index ?>">
            <button type="submit">Excluir</button>
          </form>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
