<div>
  <div>
    <div>
      <input type="text" placeholder="Procurar produtos">
      <button type="button">
        Pesquisar...
      </button>
    </div>
  </div>
  <div>
    <a href="/pages/products/new.php">
      <i></i>
      Cadastrar Produto
    </a>
  </div>
</div>

<table>
  <thead>
    <th>ID</th>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Preço</th>
  </thead>
  <tbody>
  </tbody>
</table>
