<form action="create.php" method="POST">
  <div>
    <label for="product_name">Nome:</label>
    <input type="text" name="product[name]" id="product_name">

    <label for="product_description">Descrição:</label>
    <input type="text" name="product[description]" id="product_description">

    <label for="product_brand">Marca:</label>
    <input type="text" name="product[brand]" id="product_brand">

    <label for="product_price">Preço:</label>
    <input type="number" name="product[price]" id="product_price">
  </div>

  <button type="submit">Cadastrar</button>
</form>
