<div>
    <div class="flex flex-row justify-between items-center bg-gray-100 p-4 shadow rounded-t-lg">
        <h1 class="font-bold text-gray-700"><?= $title ?></h1>
    </div>

    <div class="p-4 shadow rounded-b-lg">
        <p><span class="font-bold text-gray-800">Nome:</span> <?= $product->name  ?></p>
        <p><span class="font-bold text-gray-800">Descrição:</span> <?= $product->description  ?></p>
        <p><span class="font-bold text-gray-800">Marca:</span> <?= $product->brand  ?></p>
        <p><span class="font-bold text-gray-800">Preço:</span> R$ <?= number_format($product->price, 2, ',', '.') ?></p>
    </div>
</div>
