<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mão na Roda</title>

    <link rel="stylesheet" href="/assets/css/application.css">
    <script src="/assets/js/application.js"></script>
</head>

<body>

    <div>
        <div>
            <div>

                <?php require '_flash_message.phtml'; ?>

                <h4>
                    Login
                </h4>

                <?php require $view ?>
            </div>
        </div>

    </div>

</body>

</html>
